# Generated by Django 5.1.1 on 2024-10-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_address_gitjobuser_home_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitjobuser',
            name='about',
        ),
        migrations.AddField(
            model_name='gitjobuser',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gitjobuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
