# Generated by Django 5.1.1 on 2024-10-16 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_gitjobuser_about_gitjobuser_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitjobuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='gitjobuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='username',
        ),
        migrations.AddField(
            model_name='gitjobuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitjobuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gitjobuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
