# Generated by Django 5.1.1 on 2024-10-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_gitjobuser_options_alter_gitjobuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitjobuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
