# Generated by Django 5.1.1 on 2024-10-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_gitjobuser_experiences_gitjobuser_skills_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='gitjobuser',
            name='experiences',
            field=models.ManyToManyField(to='users.experience'),
        ),
        migrations.AddField(
            model_name='gitjobuser',
            name='skills',
            field=models.ManyToManyField(to='users.skill'),
        ),
    ]
