# Generated by Django 5.1.1 on 2024-10-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_experience_skill_remove_gitjobuser_experiences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitjobuser',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='gitjobuser',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AddField(
            model_name='gitjobuser',
            name='experiences',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='gitjobuser',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
