# Generated by Django 5.1.1 on 2024-10-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_gitjobuser_experiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitjobuser',
            name='user_type',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
