# Generated by Django 5.1.1 on 2024-10-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_gitjobuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitjobuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='gitjobuser',
            name='is_business_manager',
            field=models.BooleanField(default=False),
        ),
    ]
