# Generated by Django 5.1.1 on 2024-10-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_resume_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='users/static/uploads/'),
        ),
    ]
