# Generated by Django 5.1.1 on 2024-10-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_resume_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitjobuser',
            name='profile_picture',
            field=models.ImageField(default='static/images/default_profile_picture', upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='users/static/uploads/resumes/'),
        ),
    ]
