# Generated by Django 5.1.1 on 2024-10-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_gitjobuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitjobuser',
            name='profile_picture',
            field=models.ImageField(default='users/profile_pictures/default_profile_pic.png', upload_to='users/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='users/resumes/'),
        ),
    ]
