# Generated by Django 5.1.1 on 2024-11-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_resume_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='last_updated',
            new_name='date_uploaded',
        ),
    ]
