# Generated by Django 5.1.1 on 2024-10-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_field', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('hiring_deadline', models.DateField()),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_description', models.TextField()),
                ('core_competencies', models.TextField()),
                ('tags', models.TextField(blank=True, help_text='Enter tags separated by commas.')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
