# Generated by Django 5.1.1 on 2024-11-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_jobpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_schedule',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('project_work', 'Project Work'), ('select', 'Select')], default='select', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_field',
            field=models.CharField(choices=[('architecture_engineering', 'Architecture and Engineering'), ('arts_entertainment', 'Arts and Entertainment'), ('business_management', 'Business Management and Administration'), ('communications', 'Communications'), ('education', 'Education'), ('it', 'IT'), ('repair_maintenance', 'Repair and Maintenance'), ('agriculture', 'Agriculture'), ('health_medicine', 'Health and Medicine'), ('law_public_policy', 'Law and Public policy'), ('sales', 'Sales'), ('others', 'Others')], default='others', max_length=255),
        ),
    ]
